name: Task
type: Task
title: "[Task]: "
projects: ["entercloud-cz/4"]
description: Thrify product improvement ideas and tasks.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Task's purpose is to share ideas to improve the Thrify product or tasks to be done to deliver it.
        Task is stored by default in __Intake__ in [following view](https://github.com/orgs/entercloud-cz/projects/4/views/2).
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem statement
      description: Description of idea to implement, task to complete, or problem to solve.
    validations: { required: true }
  - type: textarea
    id: benefit
    attributes:
      label: Benefit of the task
      description: Description of the expected benefit or value of completing this task.
    validations: { required: true }
  - type: dropdown
    id: impact
    attributes:
      label: Impact of the task
      description: What is the expected impact of completing this task.
      options:
        - All customers
        - Group of customers
        - Single customer
        - Internal
    validations: { required: true }
